// All unique IPL players across seasons 2019-2024
const ALL_PLAYERS = {
  // BAT / WK
  rohit:      { name:'Rohit Sharma',       role:'BAT', bat:{avg:32,sr:140}, bowl:null,               rating:88 },
  sky:        { name:'Suryakumar Yadav',   role:'BAT', bat:{avg:34,sr:175}, bowl:null,               rating:93 },
  ishan:      { name:'Ishan Kishan',       role:'WK',  bat:{avg:28,sr:148}, bowl:null,               rating:80 },
  tilak:      { name:'Tilak Varma',        role:'BAT', bat:{avg:30,sr:142}, bowl:null,               rating:78 },
  timdavid:   { name:'Tim David',          role:'BAT', bat:{avg:22,sr:162}, bowl:null,               rating:80 },
  dekock:     { name:'Quinton de Kock',    role:'WK',  bat:{avg:31,sr:140}, bowl:null,               rating:82 },
  naman:      { name:'Naman Dhir',         role:'BAT', bat:{avg:22,sr:138}, bowl:null,               rating:70 },
  dhoni:      { name:'MS Dhoni',           role:'WK',  bat:{avg:20,sr:148}, bowl:null,               rating:84 },
  rutu:       { name:'Ruturaj Gaikwad',    role:'BAT', bat:{avg:36,sr:142}, bowl:null,               rating:87 },
  faf:        { name:'Faf du Plessis',     role:'BAT', bat:{avg:31,sr:142}, bowl:null,               rating:83 },
  raina:      { name:'Suresh Raina',       role:'BAT', bat:{avg:27,sr:138}, bowl:{econ:9.5,wpm:0.3}, rating:78 },
  watson:     { name:'Shane Watson',       role:'AR',  bat:{avg:28,sr:138}, bowl:{econ:8.8,wpm:0.9}, rating:77 },
  rayudu:     { name:'Ambati Rayudu',      role:'BAT', bat:{avg:28,sr:138}, bowl:null,               rating:76 },
  dube:       { name:'Shivam Dube',        role:'BAT', bat:{avg:28,sr:155}, bowl:{econ:9.0,wpm:0.5}, rating:79 },
  rachin:     { name:'Rachin Ravindra',    role:'BAT', bat:{avg:29,sr:138}, bowl:{econ:8.5,wpm:0.4}, rating:78 },
  sameer:     { name:'Sameer Rizvi',       role:'BAT', bat:{avg:24,sr:148}, bowl:null,               rating:72 },
  kohli:      { name:'Virat Kohli',        role:'BAT', bat:{avg:42,sr:138}, bowl:null,               rating:92 },
  ab:         { name:'AB de Villiers',     role:'WK',  bat:{avg:40,sr:158}, bowl:null,               rating:94 },
  devdutt:    { name:'Devdutt Padikkal',   role:'BAT', bat:{avg:25,sr:132}, bowl:null,               rating:72 },
  patidar:    { name:'Rajat Patidar',      role:'BAT', bat:{avg:27,sr:148}, bowl:null,               rating:77 },
  dk:         { name:'Dinesh Karthik',     role:'WK',  bat:{avg:18,sr:162}, bowl:null,               rating:75 },
  anuj:       { name:'Anuj Rawat',         role:'WK',  bat:{avg:20,sr:132}, bowl:null,               rating:67 },
  gill:       { name:'Shubman Gill',       role:'BAT', bat:{avg:36,sr:148}, bowl:null,               rating:87 },
  shreyas:    { name:'Shreyas Iyer',       role:'BAT', bat:{avg:33,sr:138}, bowl:null,               rating:83 },
  salt:       { name:'Phil Salt',          role:'WK',  bat:{avg:29,sr:158}, bowl:null,               rating:81 },
  rinku:      { name:'Rinku Singh',        role:'BAT', bat:{avg:26,sr:152}, bowl:null,               rating:78 },
  uthappa:    { name:'Robin Uthappa',      role:'WK',  bat:{avg:23,sr:138}, bowl:null,               rating:74 },
  morgan:     { name:'Eoin Morgan',        role:'BAT', bat:{avg:22,sr:130}, bowl:null,               rating:74 },
  angkrish:   { name:'A. Raghuvanshi',     role:'BAT', bat:{avg:24,sr:142}, bowl:null,               rating:72 },
  manish:     { name:'Manish Pandey',      role:'BAT', bat:{avg:23,sr:130}, bowl:null,               rating:68 },
  pant:       { name:'Rishabh Pant',       role:'WK',  bat:{avg:30,sr:148}, bowl:null,               rating:85 },
  warner:     { name:'David Warner',       role:'BAT', bat:{avg:34,sr:142}, bowl:null,               rating:84 },
  prithvi:    { name:'Prithvi Shaw',       role:'BAT', bat:{avg:27,sr:152}, bowl:null,               rating:75 },
  jfm:        { name:'J. Fraser-McGurk',  role:'BAT', bat:{avg:25,sr:168}, bowl:null,               rating:78 },
  stubbs:     { name:'Tristan Stubbs',     role:'BAT', bat:{avg:22,sr:148}, bowl:null,               rating:73 },
  porel:      { name:'Abhishek Porel',     role:'WK',  bat:{avg:22,sr:138}, bowl:null,               rating:72 },
  smith:      { name:'Steve Smith',        role:'BAT', bat:{avg:29,sr:128}, bowl:null,               rating:76 },
  jaiswal:    { name:'Yashasvi Jaiswal',   role:'BAT', bat:{avg:36,sr:163}, bowl:null,               rating:89 },
  buttler:    { name:'Jos Buttler',        role:'WK',  bat:{avg:38,sr:152}, bowl:null,               rating:88 },
  sanju:      { name:'Sanju Samson',       role:'WK',  bat:{avg:31,sr:145}, bowl:null,               rating:83 },
  parag:      { name:'Riyan Parag',        role:'BAT', bat:{avg:27,sr:145}, bowl:{econ:9.0,wpm:0.5}, rating:75 },
  hetmyer:    { name:'Shimron Hetmyer',    role:'BAT', bat:{avg:23,sr:155}, bowl:null,               rating:76 },
  jurel:      { name:'Dhruv Jurel',        role:'WK',  bat:{avg:24,sr:138}, bowl:null,               rating:73 },
  powell:     { name:'Rovman Powell',      role:'BAT', bat:{avg:19,sr:158}, bowl:null,               rating:72 },
  klrahul:    { name:'KL Rahul',           role:'WK',  bat:{avg:38,sr:142}, bowl:null,               rating:86 },
  gayle:      { name:'Chris Gayle',        role:'BAT', bat:{avg:24,sr:152}, bowl:{econ:9.0,wpm:0.3}, rating:79 },
  dhawan:     { name:'Shikhar Dhawan',     role:'BAT', bat:{avg:29,sr:128}, bowl:null,               rating:75 },
  myank:      { name:'Mayank Agarwal',     role:'BAT', bat:{avg:25,sr:138}, bowl:null,               rating:72 },
  bairstow:   { name:'Jonny Bairstow',     role:'WK',  bat:{avg:31,sr:148}, bowl:null,               rating:80 },
  prabh:      { name:'Prabhsimran Singh',  role:'WK',  bat:{avg:24,sr:138}, bowl:null,               rating:73 },
  jitesh:     { name:'Jitesh Sharma',      role:'WK',  bat:{avg:20,sr:148}, bowl:null,               rating:72 },
  rossouw:    { name:'Rilee Rossouw',      role:'BAT', bat:{avg:26,sr:152}, bowl:null,               rating:74 },
  miller:     { name:'David Miller',       role:'BAT', bat:{avg:28,sr:148}, bowl:null,               rating:80 },
  head:       { name:'Travis Head',        role:'BAT', bat:{avg:35,sr:168}, bowl:null,               rating:89 },
  abhisrh:    { name:'Abhishek Sharma',    role:'BAT', bat:{avg:28,sr:162}, bowl:{econ:9.0,wpm:0.4}, rating:78 },
  klaasen:    { name:'Heinrich Klaasen',   role:'WK',  bat:{avg:36,sr:162}, bowl:null,               rating:87 },
  williamson: { name:'Kane Williamson',    role:'BAT', bat:{avg:30,sr:130}, bowl:null,               rating:77 },
  samad:      { name:'Abdul Samad',        role:'BAT', bat:{avg:18,sr:148}, bowl:null,               rating:70 },
  saha:       { name:'Wriddhiman Saha',    role:'WK',  bat:{avg:22,sr:130}, bowl:null,               rating:72 },
  saisudar:   { name:'Sai Sudharsan',      role:'BAT', bat:{avg:32,sr:138}, bowl:null,               rating:79 },
  abhinav:    { name:'Abhinav Manohar',    role:'BAT', bat:{avg:22,sr:148}, bowl:null,               rating:71 },
  pooran:     { name:'Nicholas Pooran',    role:'WK',  bat:{avg:24,sr:162}, bowl:null,               rating:78 },
  ayush:      { name:'Ayush Badoni',       role:'BAT', bat:{avg:23,sr:140}, bowl:null,               rating:72 },

  // ALL-ROUNDERS
  hardik:     { name:'Hardik Pandya',      role:'AR',  bat:{avg:26,sr:148}, bowl:{econ:8.2,wpm:1.2}, rating:85 },
  krunal:     { name:'Krunal Pandya',      role:'AR',  bat:{avg:16,sr:130}, bowl:{econ:7.8,wpm:0.8}, rating:70 },
  pollard:    { name:'Kieron Pollard',     role:'AR',  bat:{avg:24,sr:155}, bowl:{econ:8.8,wpm:0.8}, rating:82 },
  shepherd:   { name:'Romario Shepherd',   role:'AR',  bat:{avg:18,sr:155}, bowl:{econ:8.8,wpm:1.0}, rating:72 },
  jayant:     { name:'Jayant Yadav',       role:'AR',  bat:{avg:12,sr:120}, bowl:{econ:7.8,wpm:0.7}, rating:66 },
  jadeja:     { name:'Ravindra Jadeja',    role:'AR',  bat:{avg:22,sr:132}, bowl:{econ:7.5,wpm:1.1}, rating:83 },
  moeen:      { name:'Moeen Ali',          role:'AR',  bat:{avg:24,sr:148}, bowl:{econ:7.9,wpm:1.0}, rating:78 },
  bravo:      { name:'Dwayne Bravo',       role:'AR',  bat:{avg:14,sr:135}, bowl:{econ:8.6,wpm:1.2}, rating:75 },
  shardul:    { name:'Shardul Thakur',     role:'AR',  bat:{avg:14,sr:128}, bowl:{econ:8.9,wpm:1.3}, rating:72 },
  stokes:     { name:'Ben Stokes',         role:'AR',  bat:{avg:29,sr:142}, bowl:{econ:8.5,wpm:1.0}, rating:82 },
  maxwell:    { name:'Glenn Maxwell',      role:'AR',  bat:{avg:24,sr:162}, bowl:{econ:7.8,wpm:0.9}, rating:84 },
  cameron:    { name:'Cameron Green',      role:'AR',  bat:{avg:22,sr:145}, bowl:{econ:8.8,wpm:0.8}, rating:75 },
  hasaranga:  { name:'W. Hasaranga',       role:'AR',  bat:{avg:16,sr:130}, bowl:{econ:7.6,wpm:1.5}, rating:78 },
  washington: { name:'Washington Sundar',  role:'AR',  bat:{avg:14,sr:128}, bowl:{econ:7.4,wpm:0.9}, rating:71 },
  narine:     { name:'Sunil Narine',       role:'AR',  bat:{avg:21,sr:165}, bowl:{econ:6.8,wpm:1.3}, rating:85 },
  russell:    { name:'Andre Russell',      role:'AR',  bat:{avg:22,sr:175}, bowl:{econ:9.0,wpm:1.2}, rating:86 },
  venky:      { name:'Venkatesh Iyer',     role:'AR',  bat:{avg:26,sr:148}, bowl:{econ:8.5,wpm:0.7}, rating:77 },
  ramandeep:  { name:'Ramandeep Singh',    role:'AR',  bat:{avg:14,sr:148}, bowl:{econ:9.2,wpm:0.8}, rating:68 },
  marsh:      { name:'Mitchell Marsh',     role:'AR',  bat:{avg:28,sr:152}, bowl:{econ:8.5,wpm:0.9}, rating:80 },
  axar:       { name:'Axar Patel',         role:'AR',  bat:{avg:20,sr:138}, bowl:{econ:7.5,wpm:1.2}, rating:79 },
  stoinis:    { name:'Marcus Stoinis',     role:'AR',  bat:{avg:24,sr:152}, bowl:{econ:8.8,wpm:1.0}, rating:77 },
  scurran:    { name:'Sam Curran',         role:'AR',  bat:{avg:20,sr:140}, bowl:{econ:8.2,wpm:1.3}, rating:77 },
  livi:       { name:'Liam Livingstone',   role:'AR',  bat:{avg:22,sr:158}, bowl:{econ:8.0,wpm:0.9}, rating:78 },
  hbrar:      { name:'Harpreet Brar',      role:'AR',  bat:{avg:14,sr:128}, bowl:{econ:7.8,wpm:1.0}, rating:70 },
  markram:    { name:'Aiden Markram',      role:'AR',  bat:{avg:28,sr:142}, bowl:{econ:7.8,wpm:0.8}, rating:79 },
  nitish:     { name:'Nitish K. Reddy',    role:'AR',  bat:{avg:22,sr:145}, bowl:{econ:8.8,wpm:0.9}, rating:74 },
  cummins:    { name:'Pat Cummins',        role:'AR',  bat:{avg:16,sr:138}, bowl:{econ:8.2,wpm:1.5}, rating:83 },
  shahbaz:    { name:'Shahbaz Ahmed',      role:'AR',  bat:{avg:16,sr:135}, bowl:{econ:8.0,wpm:1.0}, rating:70 },
  holder:     { name:'Jason Holder',       role:'AR',  bat:{avg:14,sr:130}, bowl:{econ:8.3,wpm:1.4}, rating:77 },
  rashid:     { name:'Rashid Khan',        role:'AR',  bat:{avg:14,sr:135}, bowl:{econ:6.5,wpm:2.0}, rating:90 },
  vijay:      { name:'Vijay Shankar',      role:'AR',  bat:{avg:18,sr:138}, bowl:{econ:8.5,wpm:0.8}, rating:70 },
  tewatia:    { name:'Rahul Tewatia',      role:'AR',  bat:{avg:20,sr:148}, bowl:{econ:8.8,wpm:0.6}, rating:71 },
  mayers:     { name:'Kyle Mayers',        role:'AR',  bat:{avg:24,sr:148}, bowl:{econ:8.5,wpm:0.8}, rating:76 },
  hooda:      { name:'Deepak Hooda',       role:'AR',  bat:{avg:22,sr:145}, bowl:{econ:9.0,wpm:0.6}, rating:72 },
  krunallsg:  { name:'Krunal Pandya',      role:'AR',  bat:{avg:16,sr:128}, bowl:{econ:7.8,wpm:0.9}, rating:73 },
  watson2:    { name:'Shane Watson',       role:'AR',  bat:{avg:28,sr:138}, bowl:{econ:8.8,wpm:0.9}, rating:77 },
  imrantahir: { name:'Imran Tahir',        role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:7.8,wpm:1.8}, rating:78 },

  // BOWLERS
  bumrah:     { name:'Jasprit Bumrah',     role:'BOWL',bat:{avg:6, sr:80},  bowl:{econ:6.8,wpm:2.0}, rating:95 },
  malinga:    { name:'Lasith Malinga',     role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:7.0,wpm:1.8}, rating:88 },
  boult:      { name:'Trent Boult',        role:'BOWL',bat:{avg:6, sr:80},  bowl:{econ:7.5,wpm:1.7}, rating:80 },
  rahulch:    { name:'Rahul Chahar',       role:'BOWL',bat:{avg:5, sr:65},  bowl:{econ:7.8,wpm:1.5}, rating:72 },
  piyush:     { name:'Piyush Chawla',      role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:7.5,wpm:1.2}, rating:68 },
  coetzee:    { name:'Gerald Coetzee',     role:'BOWL',bat:{avg:5, sr:75},  bowl:{econ:8.5,wpm:1.4}, rating:71 },
  lukewood:   { name:'Luke Wood',          role:'BOWL',bat:{avg:8, sr:90},  bowl:{econ:8.0,wpm:1.3}, rating:68 },
  alzarri:    { name:'Alzarri Joseph',     role:'BOWL',bat:{avg:5, sr:65},  bowl:{econ:8.3,wpm:1.5}, rating:70 },
  ncn:        { name:'N. Coulter-Nile',    role:'BOWL',bat:{avg:7, sr:85},  bowl:{econ:8.2,wpm:1.4}, rating:69 },
  chahar:     { name:'Deepak Chahar',      role:'BOWL',bat:{avg:10,sr:100}, bowl:{econ:7.8,wpm:1.4}, rating:75 },
  pathirana:  { name:'M. Pathirana',       role:'BOWL',bat:{avg:4, sr:65},  bowl:{econ:7.2,wpm:1.8}, rating:80 },
  tushar:     { name:'Tushar Deshpande',   role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:8.5,wpm:1.5}, rating:70 },
  simarjeet:  { name:'Simarjeet Singh',    role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:8.2,wpm:1.2}, rating:65 },
  siraj:      { name:'Mohammed Siraj',     role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:8.2,wpm:1.6}, rating:79 },
  chahal:     { name:'Yuzvendra Chahal',   role:'BOWL',bat:{avg:5, sr:75},  bowl:{econ:7.3,wpm:1.9}, rating:82 },
  topley:     { name:'Reece Topley',       role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:7.9,wpm:1.4}, rating:74 },
  yashdayal:  { name:'Yash Dayal',         role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:8.4,wpm:1.3}, rating:70 },
  jamieson:   { name:'Kyle Jamieson',      role:'BOWL',bat:{avg:8, sr:90},  bowl:{econ:8.0,wpm:1.6}, rating:75 },
  umesh:      { name:'Umesh Yadav',        role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:8.5,wpm:1.5}, rating:72 },
  steyn:      { name:'Dale Steyn',         role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:7.5,wpm:1.7}, rating:82 },
  starc:      { name:'Mitchell Starc',     role:'BOWL',bat:{avg:8, sr:100}, bowl:{econ:8.0,wpm:1.8}, rating:80 },
  harshit:    { name:'Harshit Rana',       role:'BOWL',bat:{avg:5, sr:75},  bowl:{econ:8.5,wpm:1.5}, rating:72 },
  varun:      { name:'Varun Chakravarthy', role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:7.2,wpm:1.7}, rating:79 },
  suyash:     { name:'Suyash Sharma',      role:'BOWL',bat:{avg:3, sr:50},  bowl:{econ:7.8,wpm:1.4}, rating:68 },
  lockie:     { name:'Lockie Ferguson',    role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:8.3,wpm:1.6}, rating:74 },
  kuldeep:    { name:'Kuldeep Yadav',      role:'BOWL',bat:{avg:6, sr:75},  bowl:{econ:7.3,wpm:1.8}, rating:81 },
  rabada:     { name:'Kagiso Rabada',      role:'BOWL',bat:{avg:8, sr:90},  bowl:{econ:8.0,wpm:1.8}, rating:82 },
  anrich:     { name:'Anrich Nortje',      role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:8.0,wpm:1.8}, rating:79 },
  mukesh:     { name:'Mukesh Kumar',       role:'BOWL',bat:{avg:5, sr:65},  bowl:{econ:8.3,wpm:1.4}, rating:71 },
  ishant:     { name:'Ishant Sharma',      role:'BOWL',bat:{avg:5, sr:65},  bowl:{econ:8.1,wpm:1.3}, rating:66 },
  archer:     { name:'Jofra Archer',       role:'BOWL',bat:{avg:6, sr:80},  bowl:{econ:7.3,wpm:1.9}, rating:88 },
  sandeep:    { name:'Sandeep Sharma',     role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:7.9,wpm:1.3}, rating:70 },
  avesh:      { name:'Avesh Khan',         role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:8.5,wpm:1.5}, rating:74 },
  burger:     { name:'Nandre Burger',      role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:8.2,wpm:1.4}, rating:70 },
  shreyasg:   { name:'Shreyas Gopal',      role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:7.8,wpm:1.3}, rating:68 },
  arshdeep:   { name:'Arshdeep Singh',     role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:8.3,wpm:1.6}, rating:79 },
  harshal:    { name:'Harshal Patel',      role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:8.6,wpm:1.7}, rating:77 },
  ellis:      { name:'Nathan Ellis',       role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:8.5,wpm:1.4}, rating:70 },
  shami:      { name:'Mohammed Shami',     role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:7.8,wpm:1.8}, rating:83 },
  kaverappa:  { name:'V. Kaverappa',       role:'BOWL',bat:{avg:4, sr:55},  bowl:{econ:8.8,wpm:1.3}, rating:66 },
  bhuvi:      { name:'Bhuvneshwar Kumar',  role:'BOWL',bat:{avg:6, sr:75},  bowl:{econ:7.8,wpm:1.4}, rating:76 },
  natarajan:  { name:'T Natarajan',        role:'BOWL',bat:{avg:4, sr:55},  bowl:{econ:8.0,wpm:1.5}, rating:74 },
  unadkat:    { name:'Jaydev Unadkat',     role:'BOWL',bat:{avg:5, sr:65},  bowl:{econ:8.3,wpm:1.3}, rating:68 },
  spencer:    { name:'Spencer Johnson',    role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:8.2,wpm:1.6}, rating:76 },
  noor:       { name:'Noor Ahmad',         role:'BOWL',bat:{avg:4, sr:55},  bowl:{econ:7.5,wpm:1.5}, rating:75 },
  darshan:    { name:'Darshan Nalkande',   role:'BOWL',bat:{avg:5, sr:65},  bowl:{econ:9.0,wpm:1.2}, rating:65 },
  mohsin:     { name:'Mohsin Khan',        role:'BOWL',bat:{avg:4, sr:55},  bowl:{econ:7.6,wpm:1.5}, rating:74 },
  naveen:     { name:'Naveen-ul-Haq',      role:'BOWL',bat:{avg:5, sr:65},  bowl:{econ:8.2,wpm:1.4}, rating:73 },
  bishnoi:    { name:'Ravi Bishnoi',       role:'BOWL',bat:{avg:4, sr:60},  bowl:{econ:7.5,wpm:1.7}, rating:78 },
  yashth:     { name:'Yash Thakur',        role:'BOWL',bat:{avg:4, sr:55},  bowl:{econ:8.8,wpm:1.3}, rating:66 },
};

// Season rosters: teamId_year → array of player IDs
const SEASON_ROSTERS = {
  mi_2019:  ['rohit','dekock','sky','ishan','pollard','krunal','hardik','bumrah','malinga','alzarri','rahulch','jayant'],
  mi_2020:  ['rohit','dekock','sky','ishan','hardik','pollard','krunal','bumrah','boult','ncn','rahulch','piyush'],
  mi_2021:  ['rohit','dekock','sky','ishan','hardik','pollard','krunal','bumrah','boult','rahulch','piyush','jayant'],
  mi_2022:  ['rohit','ishan','sky','tilak','timdavid','dekock','krunal','bumrah','boult','rahulch','piyush','jayant'],
  mi_2023:  ['rohit','ishan','sky','tilak','timdavid','cameron','krunal','bumrah','piyush','coetzee','lukewood','naman'],
  mi_2024:  ['rohit','ishan','sky','tilak','hardik','timdavid','shepherd','bumrah','coetzee','lukewood','piyush','naman'],

  csk_2019: ['dhoni','watson','faf','raina','rayudu','jadeja','bravo','moeen','chahar','imrantahir','shardul','simarjeet'],
  csk_2020: ['dhoni','watson','faf','raina','rayudu','jadeja','bravo','shardul','chahar','imrantahir','tushar','simarjeet'],
  csk_2021: ['dhoni','rutu','faf','raina','rayudu','jadeja','bravo','moeen','chahar','tushar','shardul','simarjeet'],
  csk_2022: ['dhoni','rutu','rachin','dube','jadeja','moeen','bravo','shardul','chahar','pathirana','tushar','simarjeet'],
  csk_2023: ['dhoni','rutu','rachin','dube','jadeja','moeen','shardul','chahar','pathirana','tushar','stokes','simarjeet'],
  csk_2024: ['dhoni','rutu','rachin','dube','jadeja','moeen','shardul','chahar','pathirana','tushar','sameer','simarjeet'],

  rcb_2019: ['kohli','ab','parthiv','moeen','washington','steyn','chahal','umesh','siraj','yashdayal','navdeep','pawan'],
  rcb_2020: ['kohli','ab','devdutt','washington','chahal','umesh','siraj','yashdayal','pawan','ishanp','navdeep','gurkeerat'],
  rcb_2021: ['kohli','ab','devdutt','maxwell','washington','hasaranga','chahal','siraj','jamieson','harshal','yashdayal','suyash'],
  rcb_2022: ['kohli','faf','dk','patidar','maxwell','cameron','hasaranga','siraj','harshal','chahal','topley','yashdayal'],
  rcb_2023: ['kohli','faf','dk','patidar','maxwell','cameron','hasaranga','siraj','topley','yashdayal','anuj','swapnil'],
  rcb_2024: ['kohli','faf','dk','patidar','maxwell','cameron','hasaranga','siraj','topley','yashdayal','anuj','swapnil'],

  kkr_2019: ['dk','gill','narine','russell','uthappa','manish','shreyas','varun','lockie','piyush','shivam_m','suyash'],
  kkr_2020: ['dk','gill','narine','russell','uthappa','morgan','venky','varun','lockie','piyush','shivam_m','suyash'],
  kkr_2021: ['dk','gill','narine','russell','uthappa','morgan','venky','varun','lockie','shubman2','cummins','suyash'],
  kkr_2022: ['shreyas','gill','narine','russell','venky','rinku','ramandeep','varun','harshit','lockie','cummins','suyash'],
  kkr_2023: ['shreyas','salt','narine','russell','venky','rinku','ramandeep','varun','harshit','starc','cummins','suyash'],
  kkr_2024: ['shreyas','salt','narine','russell','venky','rinku','ramandeep','varun','harshit','starc','angkrish','suyash'],

  dc_2019:  ['shreyas','prithvi','pant','axar','stoinis','rabada','ishant','kuldeep','anrich','tnadc','keemo','sumit'],
  dc_2020:  ['shreyas','prithvi','pant','axar','stoinis','rabada','ishant','kuldeep','anrich','tnadc','warner','sumit'],
  dc_2021:  ['shreyas','prithvi','pant','axar','stoinis','rabada','ishant','kuldeep','anrich','tnadc','warner','marsh'],
  dc_2022:  ['warner','prithvi','pant','axar','marsh','shardul','kuldeep','mukesh','anrich','ishant','tnadc','sumit'],
  dc_2023:  ['warner','jfm','pant','axar','marsh','shardul','kuldeep','mukesh','anrich','ishant','tnadc','stubbs'],
  dc_2024:  ['warner','jfm','pant','axar','marsh','shardul','kuldeep','mukesh','tnadc','stubbs','porel','sumit'],

  rr_2019:  ['sanju','buttler','smith','stokes','archer','hetmyer','unadkat','chahal','sandeep','shreyasg','rahulch','jaydev2'],
  rr_2020:  ['sanju','buttler','smith','stokes','archer','hetmyer','unadkat','chahal','sandeep','tewatia','shreyasg','jaydev2'],
  rr_2021:  ['sanju','buttler','stokes','archer','hetmyer','tewatia','morris','chahal','boult','unadkat','sandeep','shreyasg'],
  rr_2022:  ['sanju','buttler','jaiswal','parag','hetmyer','tewatia','ashwin_r','chahal','boult','avesh','sandeep','burger'],
  rr_2023:  ['sanju','buttler','jaiswal','parag','hetmyer','jurel','tewatia','chahal','boult','avesh','sandeep','burger'],
  rr_2024:  ['sanju','buttler','jaiswal','parag','hetmyer','jurel','powell','chahal','boult','avesh','sandeep','burger'],

  pbks_2019: ['klrahul','gayle','myank','maxwell','miller','shami','arshdeep','ashwin_r','murugan','mohammedsh2','ankit','sarfaraz'],
  pbks_2020: ['klrahul','gayle','myank','maxwell','pooran','shami','arshdeep','murugan','mohammedsh2','jordon','sarfaraz','ankit'],
  pbks_2021: ['klrahul','gayle','myank','pooran','deepak_h','shami','arshdeep','hbrar','murugan','bishnoi','sarfaraz','ankit'],
  pbks_2022: ['bairstow','dhawan','livi','scurran','jitesh','prabh','hbrar','rabada','arshdeep','harshal','ellis','kaverappa'],
  pbks_2023: ['bairstow','dhawan','livi','scurran','jitesh','prabh','hbrar','rabada','arshdeep','harshal','ellis','shami'],
  pbks_2024: ['bairstow','prabh','jitesh','livi','scurran','rossouw','hbrar','rabada','arshdeep','harshal','ellis','kaverappa'],

  srh_2019: ['warner','bairstow','williamson','rashid','bhuvi','natarajan','holder','shahbaz','manish','vijay','sandeep','unadkat'],
  srh_2020: ['warner','bairstow','williamson','rashid','bhuvi','natarajan','holder','shahbaz','myank','vijay','sandeep','unadkat'],
  srh_2021: ['warner','williamson','rashid','bhuvi','natarajan','holder','shahbaz','samad','vijay','sandeep','unadkat','jason_r'],
  srh_2022: ['williamson','markram','abhisrh','samad','nitish','shahbaz','bhuvi','natarajan','rashid','unadkat','vijay','sandeep'],
  srh_2023: ['markram','abhisrh','samad','nitish','shahbaz','klaasen','cummins','bhuvi','natarajan','jaydev3','vijay','sandeep'],
  srh_2024: ['head','klaasen','abhisrh','markram','samad','nitish','shahbaz','cummins','bhuvi','natarajan','jaydev3','sandeep'],

  gt_2022:  ['hardik','gill','saisudar','miller','tewatia','vijay','abhinav','rashid','shami','noor','darshan','lockie'],
  gt_2023:  ['gill','saisudar','miller','tewatia','vijay','abhinav','saha','rashid','shami','noor','spencer','darshan'],
  gt_2024:  ['gill','saisudar','miller','tewatia','vijay','abhinav','saha','rashid','shami','noor','spencer','darshan'],

  lsg_2022: ['klrahul','dekock','stoinis','mayers','hooda','ayush','pooran','krunallsg','avesh','mohsin','bishnoi','naveen'],
  lsg_2023: ['klrahul','dekock','stoinis','mayers','hooda','ayush','pooran','krunallsg','avesh','mohsin','bishnoi','naveen'],
  lsg_2024: ['klrahul','dekock','stoinis','mayers','hooda','ayush','pooran','krunallsg','mohsin','bishnoi','naveen','yashth'],
};

// Fix: some roster IDs may not exist in ALL_PLAYERS — map unknowns to a generic filler
const FILLER_PLAYERS = {
  parthiv:    { name:'Parthiv Patel',      role:'WK',  bat:{avg:18,sr:128}, bowl:null,               rating:65 },
  navdeep:    { name:'Navdeep Saini',      role:'BOWL',bat:{avg:5, sr:65},  bowl:{econ:8.5,wpm:1.4}, rating:68 },
  pawan:      { name:'Pawan Negi',         role:'AR',  bat:{avg:10,sr:120}, bowl:{econ:8.2,wpm:0.7}, rating:62 },
  ishanp:     { name:'Ishan Porel',        role:'BOWL',bat:{avg:4, sr:55},  bowl:{econ:8.8,wpm:1.2}, rating:62 },
  gurkeerat:  { name:'Gurkeerat Singh',    role:'BAT', bat:{avg:16,sr:120}, bowl:null,               rating:60 },
  swapnil:    { name:'Swapnil Singh',      role:'AR',  bat:{avg:14,sr:128}, bowl:{econ:8.0,wpm:0.7}, rating:65 },
  shivam_m:   { name:'Shivam Mavi',        role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:8.8,wpm:1.3}, rating:65 },
  shubman2:   { name:'Shubman Gill',       role:'BAT', bat:{avg:36,sr:148}, bowl:null,               rating:87 },
  keemo:      { name:'Keemo Paul',         role:'AR',  bat:{avg:14,sr:138}, bowl:{econ:8.5,wpm:1.0}, rating:66 },
  tnadc:      { name:'T Natarajan',        role:'BOWL',bat:{avg:4, sr:55},  bowl:{econ:8.0,wpm:1.5}, rating:74 },
  sumit:      { name:'Sumit Kumar',        role:'AR',  bat:{avg:12,sr:125}, bowl:{econ:8.8,wpm:0.9}, rating:64 },
  jaydev2:    { name:'Jaydev Unadkat',     role:'BOWL',bat:{avg:5, sr:65},  bowl:{econ:8.3,wpm:1.3}, rating:68 },
  jaydev3:    { name:'Jaydev Unadkat',     role:'BOWL',bat:{avg:5, sr:65},  bowl:{econ:8.3,wpm:1.3}, rating:68 },
  morris:     { name:'Chris Morris',       role:'AR',  bat:{avg:14,sr:142}, bowl:{econ:8.2,wpm:1.4}, rating:76 },
  ashwin_r:   { name:'R Ashwin',           role:'AR',  bat:{avg:12,sr:120}, bowl:{econ:7.5,wpm:1.2}, rating:74 },
  murugan:    { name:'Murugan Ashwin',     role:'BOWL',bat:{avg:4, sr:55},  bowl:{econ:7.8,wpm:1.2}, rating:66 },
  mohammedsh2:{ name:'M Shami',            role:'BOWL',bat:{avg:5, sr:70},  bowl:{econ:7.8,wpm:1.8}, rating:83 },
  jordon:     { name:'Chris Jordan',       role:'AR',  bat:{avg:10,sr:120}, bowl:{econ:8.5,wpm:1.2}, rating:68 },
  sarfaraz:   { name:'Sarfaraz Khan',      role:'BAT', bat:{avg:20,sr:135}, bowl:null,               rating:66 },
  ankit:      { name:'Ankit Rajpoot',      role:'BOWL',bat:{avg:4, sr:55},  bowl:{econ:8.8,wpm:1.2}, rating:63 },
  deepak_h:   { name:'Deepak Hooda',       role:'AR',  bat:{avg:22,sr:145}, bowl:{econ:9.0,wpm:0.6}, rating:72 },
  jason_r:    { name:'Jason Roy',          role:'BAT', bat:{avg:22,sr:145}, bowl:null,               rating:73 },
};

function resolvePlayer(id) {
  return ALL_PLAYERS[id] || FILLER_PLAYERS[id] || {
    name: id, role:'BAT', bat:{avg:15,sr:120}, bowl:null, rating:60
  };
}

// All rollable team-season combinations
const ROLLABLE_SEASONS = Object.keys(SEASON_ROSTERS).map(key => {
  const [teamId, year] = key.split('_');
  return { teamId, year: parseInt(year), key };
});

function rollTeamSeason() {
  const entry = ROLLABLE_SEASONS[Math.floor(Math.random() * ROLLABLE_SEASONS.length)];
  const team = TEAMS.find(t => t.id === entry.teamId);
  const ids = SEASON_ROSTERS[entry.key] || [];
  const players = ids.map(id => ({ ...resolvePlayer(id), id }));
  return { teamId: entry.teamId, year: entry.year, team, players };
}
